### ISSUE TITLE
m3u_modder.py does not work

### ISSUE THREAD

**Issue by merrychrishna** [ReenigneArcher/web2tv#25] opened 2022-02-21 16:07 UTC
### Describe the Bug

my settings look like this 
![image](https://user-images.githubusercontent.com/59185469/154990472-406b5c6c-35ee-4c94-8b9a-a6f0cf36ca38.png)
however, these settings only work for the plutotv.py script.

the m3u_modder.py does not create a playable m3u for converting ersatz tv m3us to be played in streamlink through xteve to emby or plex. only the plutotv.py script is working that way.

### Code Snippets

```python
C:\cygwin64\home\user\xteve2>python C:\cygwin64\home\user\xteve2\web2tv-main\m3u_modder.py -i http://localhost:8409/iptv/channels.m3u -o C:\cygwin64\home\user\xteve2\streamlink.m3u
```

### Operating System and Version

windows 10

### Python Version

Python 3.7.9

**Comment by ReenigneArcher** [comment] 2022-02-21 16:43
Duplicate of #24

**Closed as completed by ReenigneArcher** 2022-02-21 16:43 UTC
Labels: duplicate
